name: OstraTowns
description: Private plugin for Ostracraft server
author: Skylyxx
website: https://ostracraft.jimdofree.com
main: fr.ostracraft.towns.OstraTowns
version: @version@
api-version: @apiVersion@
softdepend: [ Vault ]
commands:
  town:
    aliases: [ "ville", "t", "vi" ]